<?php

namespace Database\Seeders;

use App\Models\Admin;
use App\Models\Car;
use App\Models\Sponsor;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        Admin::factory()->create([
            'name' => 'Super Admin',
            'username' => 'admin',
            'email' => 'fleet-admin@example.com',
            "password" => Hash::make("123qwe!@£QWE"),
        ]);

        User::factory()->create([
            'name' => 'Fleet User',
            'username' => 'user',
            'email' => 'user@example.com',
            'employee_number' => 'EMP0001',
            "password" => Hash::make("123qwe!@£QWE"),
        ]);

        $now = now();

        $additionalUsers = [
            [
                'name' => 'RACHELLE ANN MAY ALCANTARA CAPINA',
                'username' => 'RACHELLE ANN MAY',
                'email' => 'rachelle@riotravels.ae',
                'employee_number' => '0002',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MENCHE QUESADA PONFERRADA',
                'username' => 'MENCHE',
                'email' => 'menchi@riotravels.ae',
                'employee_number' => '9003',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'GLEXIE DAWN  REGUSANTE LABRADOR',
                'username' => 'GLEXIE DAWN ',
                'email' => 'glexie@riotravels.ae',
                'employee_number' => '9005',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'LOVELY GELENE  NAVARRO DALIGDIG',
                'username' => 'LOVELY GELENE ',
                'email' => 'gelene@riotravels.ae',
                'employee_number' => '9006',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'PRINCESS  INCAMINA SANTOYO',
                'username' => 'PRINCESS ',
                'email' => 'princess@riotravels.ae',
                'employee_number' => '9011',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ANNA MARIE ALCANTARA DE LEON',
                'username' => 'ANNA MARIE',
                'email' => 'anna@riotravels.ae',
                'employee_number' => '9015',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'AMIN AHMED AMIN HAGAG',
                'username' => 'AMIN AHMED',
                'email' => 'amin@riotravels.ae',
                'employee_number' => '9019',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MICHAEL JOHN JR. CASIPE ENRIQUEZ',
                'username' => 'MICHAEL JOHN JR.',
                'email' => 'mj@riotravels.ae',
                'employee_number' => '9021',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'KIER EVOL SANTOS LIBAO',
                'username' => 'KIER EVOL',
                'email' => 'kier@riotravels.ae',
                'employee_number' => '9025',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JULIE LUISTRO BELO',
                'username' => 'JULIE',
                'email' => 'julie@riotravels.ae',
                'employee_number' => '9026',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RYAN  DEGOMBES',
                'username' => 'RYAN',
                'email' => 'ryan@phlinktravels.com',
                'employee_number' => '9033',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'KRISTIAN SERRANO DE LUNA',
                'username' => 'KRISTIAN',
                'email' => 'kristian@riotravels.ae',
                'employee_number' => '9035',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ROSELLE SHEENA CUREG LAGGUI',
                'username' => 'ROSELLE SHEENA',
                'email' => 'sheena@riotravels.ae',
                'employee_number' => '9044',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DONNA LIEZEL ALCANTARA DE LEON',
                'username' => 'DONNA LIEZEL',
                'email' => 'finance@riotravels.ae',
                'employee_number' => '9047',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JAY WARREN PILASPILAS LOCAMBO',
                'username' => 'JAY WARREN',
                'email' => 'warren@phlinktravels.com',
                'employee_number' => '9048',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'INA MARIEJO BORLAZA GRAVINA',
                'username' => 'INA MARIEJO',
                'email' => 'ina@riotravels.ae',
                'employee_number' => '9058',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOAN MAY MANUEL CAMPIOS',
                'username' => 'JOAN MAY',
                'email' => 'joan@riotravels.ae',
                'employee_number' => '9059',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JAN ANGELO LAGRAN ASLARONA',
                'username' => 'JAN ANGELO',
                'email' => 'jan@riotravels.ae',
                'employee_number' => '9062',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DWIGHT MAGADA VILLON',
                'username' => 'DWIGHT',
                'email' => 'dwight@riotravels.ae',
                'employee_number' => '9064',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ELIAMAE VICENTINO PORCADILLA',
                'username' => 'ELIAMAE',
                'email' => 'eliamae@riotravels.ae',
                'employee_number' => '9065',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JONEL ESPINOZA GARCIA',
                'username' => 'JONEL',
                'email' => 'jonel@riotravels.ae',
                'employee_number' => '9067',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JIMMUEL QUIJANO CASTRO',
                'username' => 'JIMMUEL',
                'email' => 'jimmuel@riotravels.ae',
                'employee_number' => '9071',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SHARENE  ANGELES',
                'username' => 'SHARENE',
                'email' => 'sharene@riotravels.ae',
                'employee_number' => '9072',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CHRISTIAN HERBON LOPEZ',
                'username' => 'CHRISTIAN',
                'email' => 'christian@riotravels.ae',
                'employee_number' => '9076',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOANNA MARIE BERNAL CORTEZ',
                'username' => 'JOANNA MARIE',
                'email' => 'joannamarie@riotravels.ae',
                'employee_number' => '9078',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MIA VILLANUEVA SANTIANEZ',
                'username' => 'MIA',
                'email' => 'mia@phlinktravels.com',
                'employee_number' => '9080',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SANDRA TRISHA APOLINARIO ARTUZ',
                'username' => 'SANDRA TRISHA',
                'email' => 'trisha@riotravels.ae',
                'employee_number' => '9081',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SHERYL JURADO GARIN',
                'username' => 'SHERYL',
                'email' => 'sheryl@riotravels.ae',
                'employee_number' => '9082',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ROCHELLE GALANG RUZ',
                'username' => 'ROCHELLE',
                'email' => 'rochelle@riotravels.ae',
                'employee_number' => '9083',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'AMNA MARIYAM  ABURABAH',
                'username' => 'AMNA MARIYAM',
                'email' => 'amna@riotravels.ae',
                'employee_number' => '9084',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ANJANA  MOHAN',
                'username' => 'ANJANA',
                'email' => 'anjana@riotravels.ae',
                'employee_number' => '9086',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ERIKA MOLINA DAPADAP',
                'username' => 'ERIKA',
                'email' => 'erika@riotravels.ae',
                'employee_number' => '9087',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JERWIN JED VALENZUELA DASAL',
                'username' => 'JERWIN JED',
                'email' => 'jerwin@riotravels.ae',
                'employee_number' => '9088',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ASHLEY NICOLE  CANLAS',
                'username' => 'ASHLEY NICOLE',
                'email' => 'ashley@riotravels.ae',
                'employee_number' => '9090',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SHERA GARCIA ACOBA',
                'username' => 'SHERA',
                'email' => 'hr@riotravels.ae',
                'employee_number' => '9091',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ANGELICA BORLAZA GRAVINA',
                'username' => 'ANGELICA',
                'email' => 'angelica@riotravels.ae',
                'employee_number' => '9092',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MARK ALLEN  CAGUIOA',
                'username' => 'MARK ALLEN',
                'email' => 'markallen@riotravels.ae',
                'employee_number' => '9093',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'WALID ABDULLAH YAHYA  AL-SURAIHI',
                'username' => 'WALID ABDULLAH YAHYA',
                'email' => 'walid@riotravels.ae',
                'employee_number' => '9095',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'HAMID  KHAN',
                'username' => 'HAMID',
                'email' => 'hamid@riotravels.ae',
                'employee_number' => '9096',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CHESTER RAY  DASIG',
                'username' => 'CHESTER RAY',
                'email' => 'chester@riotravels.ae',
                'employee_number' => '9097',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MARIBEL  SUMAGAYSAY',
                'username' => 'MARIBEL',
                'email' => 'maribel@riotravels.ae',
                'employee_number' => '9099',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MIRASOL  QUINAGORAN',
                'username' => 'MIRASOL',
                'email' => 'mirasol@riotravels.ae',
                'employee_number' => '9100',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CHARRY LEI  DUENAS',
                'username' => 'CHARRY LEI',
                'email' => 'charry@riotravels.ae',
                'employee_number' => '9102',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOHN EDWARD  ENGAY',
                'username' => 'JOHN EDWARD',
                'email' => 'edward@riotravels.ae',
                'employee_number' => '9103',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOHN ACXEL  PERALTA',
                'username' => 'JOHN ACXEL',
                'email' => 'johnacxel@riotravels.ae',
                'employee_number' => '9105',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SEIF ALLAH  GHAZOUANI',
                'username' => 'SEIF ALLAH',
                'email' => 'saif@xtrevo.com',
                'employee_number' => '9106',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MOHAMED IRFAN  MOHAMED IRSHAD',
                'username' => 'MOHAMED IRFAN',
                'email' => 'irfan@riotravels.com',
                'employee_number' => '9107',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ZIAD  BUTT',
                'username' => 'ZIAD',
                'email' => 'ziad@riotravels.ae',
                'employee_number' => '9108',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOSEPH  CASTRO',
                'username' => 'JOSEPH',
                'email' => 'joseph@riotravels.ae',
                'employee_number' => '9109',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ARIEL  BOTIO',
                'username' => 'ARIEL',
                'email' => 'ariel@riotravels.ae',
                'employee_number' => '9110',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MARITES PLAZA LANABAN',
                'username' => 'MARITES',
                'email' => 'marites@phlinktravels.com',
                'employee_number' => '1001',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'FRANCES ANDREA FELIX GUTIERREZ',
                'username' => 'FRANCES ANDREA',
                'email' => 'frances@riotravels.ae',
                'employee_number' => '1017',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RON ROSE PERALTA CORTEZ',
                'username' => 'RON ROSE',
                'email' => 'ronrose@phlinktravels.com',
                'employee_number' => '1018',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RICO BUCAD ALCANTARA',
                'username' => 'RICO',
                'email' => 'rico@phlinktravels.com',
                'employee_number' => '1020',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOHN PAUL DE VERA BALBERAN',
                'username' => 'JOHN PAUL',
                'email' => 'johnpaul@phlinktravels.com',
                'employee_number' => '1025',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JEROME BANTOG LACSON',
                'username' => 'JEROME',
                'email' => 'jerome@phlinktravels.com',
                'employee_number' => '1031',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ALYNDA PATIAG JAPON',
                'username' => 'ALYNDA',
                'email' => 'alynda@phlinktravels.com',
                'employee_number' => '1034',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RUTH PUBLICO ALIBARBAR',
                'username' => 'RUTH',
                'email' => 'ruth@phlinktravels.com',
                'employee_number' => '1035',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ELDRIN JAY FLORES MALLARI',
                'username' => 'ELDRIN JAY',
                'email' => 'eldrin@phlinktravels.com',
                'employee_number' => '1036',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'FATIMA PASCUA MANCIA',
                'username' => 'FATIMA',
                'email' => 'fatima@phlinktravels.com',
                'employee_number' => '1039',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MARIEL RUBIALES MEREGILLA',
                'username' => 'MARIEL',
                'email' => 'mariel@phlinktravels.com',
                'employee_number' => '1040',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'TRIZIA LAGDA REDONDO',
                'username' => 'TRIZIA',
                'email' => 'trizia.redondo@phlinktravels.com',
                'employee_number' => '1043',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RAPHAEL JORDAN MENDOZA UY',
                'username' => 'RAPHAEL JORDAN',
                'email' => 'raphael@phlinktravels.com',
                'employee_number' => '1045',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CHRISTOPHER JOHN  LEYNES',
                'username' => 'CHRISTOPHER JOHN',
                'email' => 'christopherjohn@phlinktravels.com',
                'employee_number' => '1048',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'CALIXTO KENNETH BALTAZAR SALOMON',
                'username' => 'CALIXTO KENNETH',
                'email' => 'calixto@phlinktravels.com',
                'employee_number' => '1049',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BRYAN  MURILLO',
                'username' => 'BRYAN',
                'email' => 'bryan@phlinktravels.com',
                'employee_number' => '1050',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NATHANIEL  FERRER',
                'username' => 'NATHANIEL',
                'email' => 'nathaniel@phlinktravels.com',
                'employee_number' => '1052',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RISHLYN FABUNAN CALARA',
                'username' => 'RISHLYN',
                'email' => 'rishlyn@phlinktravels.com',
                'employee_number' => '1054',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ANGELINE  SAMPANG',
                'username' => 'ANGELINE',
                'email' => 'angeline@phlinktravels.com',
                'employee_number' => '1055',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RICARDO  PAGUIRIGAN',
                'username' => 'RICARDO',
                'email' => 'rica@phlinktravels.com',
                'employee_number' => '1058',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MAILA  SALAS',
                'username' => 'MAILA',
                'email' => 'maila@phlinktravels.com',
                'employee_number' => '1059',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'GARTH DANIEL  ACOSTA',
                'username' => 'GARTH DANIEL',
                'email' => 'garth@phlinktravels.com',
                'employee_number' => '1060',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'THEA KREZYL  PEREZ',
                'username' => 'THEA KREZYL',
                'email' => 'thea@phlinktravels.com',
                'employee_number' => '1061',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DIANNE  RILLERA',
                'username' => 'DIANNE',
                'email' => 'dianne@phlinktravels.com',
                'employee_number' => '1063',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RAYMART  MEDINA',
                'username' => 'RAYMART',
                'email' => 'raymart@phlinktravels.com',
                'employee_number' => '1065',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MUSTAFA YOUSEF  ABU HAJAR',
                'username' => 'MUSTAFA YOUSEF',
                'email' => 'mhajer@netronsolutions.com',
                'employee_number' => '2000',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'AMANI  AL HIARY',
                'username' => 'AMANI',
                'email' => 'amani.i.hiary@netronsolutions.com',
                'employee_number' => '2003',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JACKLEEN  KAMEL',
                'username' => 'JACKLEEN',
                'email' => 'jackleen.kamel@netronsolutions.com',
                'employee_number' => '2002',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RAMI  AL BANAA',
                'username' => 'RAMI',
                'email' => 'rami@netronsolutions.com',
                'employee_number' => '2007',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ABDULLAH  MASWADEH',
                'username' => 'ABDULLAH',
                'email' => 'abdullah.maswadeh@netronsolutions.com',
                'employee_number' => '2010',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MUATH  ISHBEEB',
                'username' => 'MUATH',
                'email' => 'moath.shabeeb@netronsolutions.com',
                'employee_number' => '2011',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MOHAMAD  DAOOD',
                'username' => 'MOHAMAD',
                'email' => 'mohammad.daood@xtrevo.com',
                'employee_number' => '2012',
                'password' => '$2y$12$.86LrVPPzxkmGFyogUYCReX0.KHFxaLlHP.qIgYCWhVrsgT7Q8P1G',
                'role' => 'user',
                'is_active' => true,
                'remember_token' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        User::insert($additionalUsers);

        User::factory(5)->create();

        $sponsors = Sponsor::factory(3)->create();

        Car::factory(5)->create()->each(function (Car $car) use ($sponsors) {
            if ($sponsors->isNotEmpty() && fake()->boolean(40)) {
                $car->update([
                    'is_company_owned' => false,
                    'sponsor_id' => $sponsors->random()->id,
                ]);
            }
        });
    }
}
